# Generated by Django 3.1.6 on 2021-02-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20210216_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
